"""empty message

Revision ID: 229415c8ad6b
Revises: 0e3584072c53
Create Date: 2020-07-15 23:56:02.157481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229415c8ad6b'
down_revision = '0e3584072c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mark', table_name='marks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('mark', 'marks', ['mark'], unique=True)
    # ### end Alembic commands ###
