"""empty message

Revision ID: da89314e3025
Revises: f08e50345d86
Create Date: 2020-07-14 01:11:39.501989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da89314e3025'
down_revision = 'f08e50345d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'students', ['student_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    # ### end Alembic commands ###
